### ISSUE TITLE
load Generator weights

### ISSUE THREAD

**Issue by ding-s-h** [SubarnaTripathi/ReverseGAN#2]
Hi, thanks for sharing. I have a question about the loading G's weights part,
in "load_new" function, in the line:
     checkpoint_include_scopes=["g_h0_lin", "g_h1", "g_h2", "g_h3"] 
why isn't "g_h4" included? Thanks.
@SubarnaTripathi

**Comment by SubarnaTripathi** [comment]
Those lines are indeed redundant when I was trying to debug and load all but the last layer weights.  In line #1020, the whole whole checkpoint is restored.

**Comment by ding-s-h** [comment]
Thanks for clarifying that.
